name: CI
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone code
        uses: actions/checkout@v3
      - name: Install tool build
        uses: docker://alpine:3.8
      - name: Install tool
        run: apk add gcc-avr cmake make

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
