name: CI
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone code
        uses: actions/checkout@v3
      - name: Install tool
        run: |
          sudo apt update
          sudo apt install -y gcc-avr avr-libc cmake make
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ../
          make run

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
